apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hj1d170s4-python 
  janus-idp.io/tekton: hj1d170s4-python
  backstage.io/kubernetes-id: hj1d170s4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hj1d170s4-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  